name: deploy-container

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
